-- Tünel + Yazılı modülleri için içerik yaşam döngüsü audit aksiyonları.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TUNNEL_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TUNNEL_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TUNNEL_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TUNNEL_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WRITTEN_PUBLISHED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WRITTEN_UNPUBLISHED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WRITTEN_UPDATED';
