-- E-Sınıf (okul) hassas işlemleri için audit aksiyonları.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_USER_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_USERS_BULK_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_USER_PASSWORD_RESET';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_USER_ACTIVE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_SUBMISSION_GRADED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_ORG_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SCHOOL_ORG_DELETED';
